import RelatedEntity from './relatedentity';

const Employee = `
  type Employee {
    _Link: String
    _Certifications: String
    _Affiliations: String
    _Registrations: String
    _Skills: String
    _Resumes: String
    _Degrees: String
    _Media: String
    _Contacts: String
    _Companies: String
    _Projects: String
    _Opportunities: String
    employeeID: String
    affiliationsDetail: [Affiliation]
    aia: String
    birthday: String
    birthdayDate: String
    birthdayMonth: String
    birthdayPrivate: String
    billingCategory: String
    certifications: String
    certificationsDetail: [Certification]
    companyCount: Int
    contactCount: Int
    country: String
    daM_EM_CustDat01: String
    daM_EM_CustNum01: Int
    daM_EM_CustTxt01: String
    daM_EM_CustTxt02: String
    daM_EM_CustTxt03: String
    daM_EM_CustVar01: String
    daM_EM_CustVar02: String
    daM_EM_CustVar03: String
    daM_EM_CustVar04: String
    daM_EM_CustVar05: String
    daM_EmployeeRecord: String
    daM_EntityCategory: String
    daM_EntityID: String
    daM_ImageCount: Int
    degreesEarned: String
    degreesEarnedDetail: [Degree]
    department: String
    discipline: String
    email: String
    employeeAdvocate: String
    employeeInDAMSystem: String
    employeeInLOBSystem: String
    employeeInPIMSystem: String
    employeeNumber: String
    employeeProfile_Custom01: String
    employeeProfile_Custom02: String
    employeeProfile_Custom03: String
    employeeProfile_Custom04: String
    employeeProfile_Custom05: String
    employeeProfile_Custom06: String
    employeeProfile_Custom07: String
    employeeProfile_Custom08: String
    employeeProfile_Custom09: String
    employeeProfile_Custom10: String
    employeeCompanies: [RelatedEntity]
    employeeContacts: [RelatedEntity]
    employeeOpportunities: [RelatedEntity]
    employeeProjects: [RelatedEntity]
    employeeType: String
    fax: String
    firmName: String
    firstName: String
    fullName: String
    hireDate: String
    homeAddress1: String
    homeAddress2: String
    homeAddress3: String
    homeAddress4: String
    homeCity: String
    homeCountry: String
    homeState: String
    homeZip: String
    hoursPerWeek: String
    lastName: String
    leedAccredited: String
    licensesAndRegistrations: String
    registrationsDetail: [Registration]
    loB_EM_CustDat01: String
    loB_EM_CustDat02: String
    loB_EM_CustDat03: String
    loB_EM_CustDat04: String
    loB_EM_CustDat05: String
    loB_EM_CustNum01: String
    loB_EM_CustNum02: String
    loB_EM_CustNum03: String
    loB_EM_CustNum04: String
    loB_EM_CustNum05: String
    loB_EM_CustTxt01: String
    loB_EM_CustTxt02: String
    loB_EM_CustTxt03: String
    loB_EM_CustTxt04: String
    loB_EM_CustTxt05: String
    loB_EM_CustVar01: String
    loB_EM_CustVar02: String
    loB_EM_CustVar03: String
    loB_EM_CustVar04: String
    loB_EM_CustVar05: String
    loB_EM_CustVar06: String
    loB_EM_CustVar07: String
    loB_EM_CustVar08: String
    loB_EM_CustVar09: String
    loB_EM_CustVar10: String
    loB_EM_CustVar11: String
    loB_EM_CustVar12: String
    loB_EM_CustVar13: String
    loB_EM_CustVar14: String
    loB_EM_CustVar15: String
    loB_EmployeeRecord: String
    loB_EntityCategory: String
    loB_EntityID: String
    mobilePhone: String
    ncarb: String
    office: String
    opportunityCount: Int
    org: String
    orgName: String
    personalBio: String
    piM_EM_CustDat01: String
    piM_EM_CustNum01: String
    piM_EM_CustTxt01: String
    piM_EM_CustTxt02: String
    piM_EM_CustTxt03: String
    piM_EM_CustVar01: String
    piM_EM_CustVar02: String
    piM_EM_CustVar03: String
    piM_EM_CustVar04: String
    piM_EM_CustVar05: String
    piM_EmployeeRecord: String
    piM_EntityCategory: String
    piM_EntityID: String
    preferredFirstName: String
    professionalAffiliations: String
    profileLastModifiedBy: String
    projectCount: Int
    projectRoles: String
    projectTypes: String
    registeredArchitect: String
    resourceFor: String
    showInCompanyDirectory: String
    skills: String
    state: String
    sourceSystem: String
    status: String
    streetAddress1: String
    streetAddress2: String
    streetAddress3: String
    streetAddress4: String
    title: String
    workPhone: String
    workPhoneExtension: String
    workPhonePlusExtension: String
    wsS_EmployeeRecordCustom01: String
    wsS_EmployeeRecordCustom02: String
    wsS_EmployeeRecordCustom03: String
    wsS_EmployeeResumes: String
    yearsWithFirm: Int
    zip: String
    priorYearsWithFirm: Int
    primaryImageID: String
    modDate: String
  }
  type Affiliation {
    recordID: ID
    employeeID: ID
    affiliation: String
    membershipNo: String
    dateExpires: String
    modDate: String
  }
  type Certification {
    recordID: ID
    employeeID: String
    certification: String
    certifyingAgency: String
    dateEarned: String
    modDate: String
  }
  type Degree {
    recordID: ID
    employeeID: String
    degree: String
    institution: String
    yearEarned: Int
    modDate: String
    showInSynthesis: String
  }
  type Registration {
    recordID: ID
    employeeID: String
    registration: String
    registrationNo: String
    stateRegistered: String
    dateEarned: String
    dateExpires: String
    lastRenewed: String
    modDate: String
  }
`;

export default [Employee, RelatedEntity];
