const Inputs = `
    input ProjectURLParams {
        perPage: Int
        pageNum: Int
        status: String
        name: String
        chargeType: String
        city: String
        country: String
        clientID: String
        clientName: String
        minCompanyCount: Int
        maxCompanyCount: Int
        minConstructionCompletionDate: String
        maxConstructionCompletionDate: String
        minConstructionCost: Float
        maxConstructionCost: Float
        minContactCount: Int
        maxContactCount: Int
        minContractDate: String
        maxContractDate: String
        contractor: String
        country: String
        DAM_EntityCategory: String
        DAM_EntityID: String
        minDam_ImageCount: Int
        maxDAM_ImageCount: Int
        minDAM_PR_CustDat01: String
        maxDAM_PR_CustDat01: String
        minDAM_PR_CustNum01: Float
        maxDAM_PR_CustNum01: Float
        minEmployeeCount: Int
        maxEmployeeCount: Int
        daM_PR_CustTxt01: String
        daM_PR_CustTxt02: String
        daM_PR_CustTxt03: String
        daM_PR_CustVar01: String
        daM_PR_CustVar02: String
        daM_PR_CustVar03: String
        daM_PR_CustVar04: String
        daM_PR_CustVar05: String
        daM_ProjectRecord: String
        LEEDCertificationLevel: String
        LEEDCertificationStatus: String
        LEEDProgram: String
        LEEDProject: String
        loB_PR_CustTxt01: String
        loB_PR_CustTxt02: String
        loB_PR_CustTxt03: String
        loB_PR_CustTxt04: String
        loB_PR_CustTxt05: String
        loB_PR_CustVar01: String
        loB_PR_CustVar02: String
        loB_PR_CustVar03: String
        loB_PR_CustVar04: String
        loB_PR_CustVar05: String
        loB_PR_CustVar06: String
        loB_PR_CustVar07: String
        loB_PR_CustVar08: String
        loB_PR_CustVar09: String
        loB_PR_CustVar10: String
        loB_PR_CustVar11: String
        loB_PR_CustVar12: String
        loB_PR_CustVar13: String
        loB_PR_CustVar14: String
        loB_PR_CustVar15: String
        loB_ProjectPlan: String
        marketingName: String
        marketingTier: String
        office: String
        org: String
        orgName: String
        parentProject: String
        parentProjectNumber: String
        pic: String
        picNumber: String
        PIM_EntityCategory: String
        PIM_EntityID: String
        minPIM_PR_CustDat01: String
        maxPIM_PR_CustDat01: String
        minPIM_PR_CustNum01: Float
        maxPIM_PR_CustNum01: Float
        PIM_PR_CustTxt01: String
        PIM_PR_CustTxt02: String
        PIM_PR_CustTxt03: String
        PIM_PR_CustVar01: String
        PIM_PR_CustVar02: String
        PIM_PR_CustVar03: String
        PIM_PR_CustVar04: String
        PIM_PR_CustVar05: String
        PIM_ProjectRecord: String
        PIM_ProjectWebsite: String
        profileLastModifiedBy: String
        projectAliases: String
        projectDeliveryMethod: String
        projectFolderLocation: String
        projectInDAMSystem: String
        projectInLOBSystem: String
        projectInPIMSystem: String
        projectManager: String
        projectManagerNumber: String
        projectName: String
        projectNumber: String
        projectNumberDisplay: String
        projectPhase: String
        projectProfile_Custom01: String
        projectProfile_Custom02: String
        projectProfile_Custom03: String
        projectProfile_Custom04: String
        projectProfile_Custom05: String
        projectProfile_Custom06: String
        projectProfile_Custom07: String
        projectProfile_Custom08: String
        projectProfile_Custom09: String
        projectProfile_Custom10: String
        projectRole: String
        projectType: String
        publicSector: String
        sourceSystem: String
        minSquareFootage: Int
        maxSquareFootage: Int
        state: String
        status: String
        streetAddress: String
        minTotalProjectCost: Int
        maxTotalProjectCost: Int
        wsS_ProjectContracts: String
        wsS_ProjectPresentations: String
        wsS_ProjectProposals: String
        wsS_ProjectRecordCustom01: String
        wsS_ProjectRecordCustom02: String
        wsS_ProjectRecordCustom03: String
        wsS_ProjectRecordSets: String
        wsS_ProjectSheets: String
        minYearCompleted: Int
        maxYearCompleted: Int
        zip: String
        primaryImageID: String
        minDescriptionCount: Int
        maxDescriptionCount: Int
        minModDate: String
        maxModDate: String
        minLatitude: Float
        maxLatitude: Float
        minlongitude: Float
        maxlongitude: Float
        hasLatLon: Int
        apiFilter: Int
    }
  `
  export default Inputs;